services:
  api:
    build: .
    ports:
      - "0.0.0.0:3000:8000"  # Bind to all interfaces for external access
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - ENV=production
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "0.0.0.0:80:80"  # Frontend on port 80
    depends_on:
      - api
    restart: unless-stopped
