services:
  shipping-api:
    build:
      context: .
      dockerfile: Dockerfile.complete
    ports:
      - "80:80"      # Frontend
      - "3000:3000"  # API (optional direct access)
    restart: unless-stopped
    environment:
      - ENV=production
    volumes:
      - ./app/shipments.db:/app/app/shipments.db  # Persist database
