services:
  # Unified application (Frontend + Backend + Nginx)
  app:
    build:
      context: .
      dockerfile: Dockerfile.unified
    ports:
      - "${PORT:-8080}:80"
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./shipments.db}
      - SECRET_KEY=${SECRET_KEY:-change-in-production}
      - DEBUG=${DEBUG:-false}
    volumes:
      - ./shipments.db:/app/shipments.db
    restart: unless-stopped
    container_name: shipments-unified
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3